# Generated by Django 5.1.15 on 2026-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_code",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="email verification code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_code_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="email verification code expires at"
            ),
        ),
    ]
