# Generated by Django 5.1.15 on 2026-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True,
                help_text="Hosted checkout URL from the payment provider (e.g. Pesaflow iframe).",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("pesaflow", "Pesaflow"),
                    ("mpesa", "M-Pesa"),
                    ("ecitizen", "eCitizen"),
                    ("visa", "Visa"),
                    ("mastercard", "Mastercard"),
                    ("mock", "Mock (Testing)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
