# Generated by Django 5.1.15 on 2026-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_pesaflow_provider_and_checkout_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_html",
            field=models.TextField(
                blank=True,
                help_text="Raw hosted-checkout HTML fetched from the provider once at invoice creation (Pesaflow: format=iframe) — served back verbatim by PaymentCheckoutFrameView. Not re-fetchable: billRefNumber must be unique, so we can't just call the provider again if this is missing.",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(
                blank=True,
                help_text="Iframe src for the frontend to embed — our own PaymentCheckoutFrameView, not the provider's URL directly.",
                max_length=500,
            ),
        ),
    ]
