# Generated by Django 5.1.15 on 2026-07-13 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("categories", "Categories"), ("images", "Images")], max_length=20
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total", models.IntegerField(default=0)),
                ("created", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("conflicts", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetSyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, help_text="Legacy image_id — the dedupe key", unique=True
                    ),
                ),
                (
                    "external_refno",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Legacy image_refno (e.g. 305/120) — physical print reference. NOT unique, may be absent; provenance metadata only, never an identity key.",
                        max_length=50,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 of the normalised source record; unchanged checksum → skip on re-sync",
                        max_length=64,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Raw legacy record, verbatim. Unmapped fields (iptc_scene, genre, dimensions…) live here.",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Set by editors after curating an asset locally. Locked assets are never overwritten by sync; conflicts are logged instead.",
                    ),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_record",
                        to="assets.digitalasset",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["external_refno"], name="ingestion_a_externa_30abbf_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="LegacyCodeMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("PHTMainCategory", "Main category → Collection"),
                            ("PHTSubCategory", "Subcategory → Category"),
                        ],
                        max_length=30,
                    ),
                ),
                ("code", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_codes",
                        to="assets.category",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_codes",
                        to="assets.collection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["item_type", "code"], name="ingestion_l_item_ty_15f297_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("item_type", "code"), name="uniq_legacy_code")
                ],
            },
        ),
    ]
