# Generated by Django 5.1.15 on 2026-07-13 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="KNA category code, e.g. '1', '10'.", max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category. NULL for top-level main categories.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="assets.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="DigitalAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("asset_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("caption", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("photograph", "Photograph"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("pdf", "PDF"),
                            ("newspaper", "Newspaper"),
                            ("document", "Document"),
                        ],
                        default="photograph",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("restricted", "Restricted"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("photographer", models.CharField(blank=True, max_length=255)),
                ("photographer_credit", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("copyright_holder", models.CharField(blank=True, max_length=255)),
                ("publication_date", models.DateField(blank=True, db_index=True, null=True)),
                ("capture_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.category",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.collection",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="assets", to="assets.tag"),
                ),
            ],
            options={
                "verbose_name": "Digital Asset",
                "verbose_name_plural": "Digital Assets",
            },
        ),
        migrations.CreateModel(
            name="AssetVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("variant_name", models.CharField(max_length=100)),
                ("storage_path", models.CharField(max_length=500)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="assets.digitalasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("keywords", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, default="Kenya", max_length=100)),
                ("event_name", models.CharField(blank=True, max_length=255)),
                ("historical_period", models.CharField(blank=True, max_length=100)),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, default="en", max_length=50)),
                ("legacy_image_id", models.UUIDField(blank=True, null=True)),
                ("intellectual_genre", models.CharField(blank=True, max_length=100)),
                ("iptc_scene", models.CharField(blank=True, max_length=100)),
                ("image_source_type", models.CharField(blank=True, max_length=100)),
                ("image_logos", models.CharField(blank=True, max_length=255)),
                ("creator_job_title", models.CharField(blank=True, max_length=100)),
                ("image_dimensions", models.CharField(blank=True, max_length=100)),
                ("image_remarks", models.TextField(blank=True)),
                ("main_category_code", models.IntegerField(blank=True, null=True)),
                ("sub_category_code", models.IntegerField(blank=True, null=True)),
                ("thumbnails", models.JSONField(blank=True, default=list)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="assets.digitalasset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Asset Metadata",
            },
        ),
    ]
