# Generated by Django 5.1.15 on 2026-07-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitalasset",
            name="asset_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
