# Generated by Django 5.1.15 on 2026-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_digitalasset_asset_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="digitalasset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Digital Asset",
                "verbose_name_plural": "Digital Assets",
            },
        ),
    ]
