# Generated by Django 5.1.15 on 2026-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_alter_digitalasset_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalasset",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
