# Generated by Django 5.1.15 on 2026-07-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_digitalasset_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cover_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Curated banner image for this category's card. Leave empty to auto-use the newest published asset.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="assets.digitalasset",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="cover_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Curated banner image for this collection's card. Leave empty to auto-use the newest published asset.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="assets.digitalasset",
            ),
        ),
    ]
