# Generated by Django 5.1.15 on 2026-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_category_cover_asset_collection_cover_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetmetadata",
            name="date_digitized",
            field=models.DateField(
                blank=True,
                help_text="When KNA digitised the physical print (source's date_image_injested). Shown when the original publication date is unknown.",
                null=True,
            ),
        ),
    ]
