# Generated by Django 5.1.15 on 2026-07-20 09:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_digitalasset_search_vector_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetmetadata",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["location"], name="assetmeta_loc_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
